import { IonBackButton, IonButtons, IonContent, IonHeader, IonItem, IonLabel, IonList, IonPage, IonTitle, IonToolbar, withIonLifeCycle } from '@ionic/react';
import React, { createRef } from 'react';
import '../styles/Lagal.scss';

class Legal extends React.Component {

    constructor(props) {
        super(props);
        this.contentRef = createRef();
        this.termsRef = createRef();
        this.privacyRef = createRef();
        this.gdprRef = createRef();
        this.state = {
            credits: [
                {
                    name: "Map Box",
                    type: "Map Tile Server",
                    description: "Map Tile Server",
                    link: "https://www.mapbox.com/legal/tos/"
                }, {
                    name: "OpenStreetMaps",
                    type: "Map Tile Server",
                    description: "Map Tile Server",
                    link: "https://operations.osmfoundation.org/policies/tiles/",
                }, {
                    name: "Google Maps",
                    type: "Static maps, geocoding and reverse-geocoding",
                    description: "Static maps, geocoding and reverse-geocoding",
                    link: "https://cloud.google.com/maps-platform/terms",
                }, {
                    name: "Nominatim",
                    type: "Geocoding and reverse-geocoding",
                    description: "Geocoding and reverse-geocoding",
                    link: "https://operations.osmfoundation.org/policies/nominatim/",
                }, {
                    name: "Flaticon Icons",
                    type: "Icons from different sources",
                    description: `
                        Font generated by <a href="https://www.flaticon.com">flaticon.com</a>. <p>Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="098-park-1" href="https://www.flaticon.com/authors/smashicons">Smashicons</a>, <a data-file="122-toilet-paper" href="http://www.freepik.com">Freepik</a>, <a data-file="118-exhibition-1" href="https://www.flaticon.com/authors/kiranshastry">Kiranshastry</a>, <a data-file="006-city-hall" href="https://www.flaticon.com/authors/creaticca-creative-agency">Creaticca Creative Agency</a>, <a data-file="058-hospital" href="https://www.flaticon.com/authors/good-ware">Good Ware</a>, <a data-file="115-cinema" href="https://www.flaticon.com/authors/srip">srip</a>, <a data-file="021-enterprise" href="https://www.flaticon.com/authors/geotatah">geotatah</a>, <a data-file="120-car-crash" href="https://www.flaticon.com/authors/monkik">monkik</a>, <a data-file="086-laptop" href="https://www.flaticon.com/authors/those-icons">Those Icons</a>, <a data-file="100-tooth" href="https://www.flaticon.com/authors/smalllikeart">smalllikeart</a>, <a data-file="074-book" href="https://www.flaticon.com/authors/surang">surang</a>, <a data-file="114-museum-1" href="https://www.flaticon.com/authors/payungkead">Payungkead</a>, <a data-file="043-dish" href="https://www.flaticon.com/authors/pause08">Pause08</a>, <a data-file="071-wifi" href="https://www.flaticon.com/authors/pixel-perfect">Pixel perfect</a>, <a data-file="046-shopping-bag" href="https://www.flaticon.com/authors/darius-dan">Darius Dan</a>, <a data-file="079-running" href="https://www.flaticon.com/authors/photo3idea-studio">photo3idea_studio</a>, <a data-file="117-spotlights" href="https://www.flaticon.com/authors/pongsakornred">pongsakornRed</a>, <a data-file="075-book-1" href="https://www.flaticon.com/authors/mavadee">mavadee</a>, <a data-file="112-dance" href="https://www.flaticon.com/authors/wanicon">wanicon</a>, <a data-file="096-cloth" href="https://www.flaticon.com/authors/iconixar">iconixar</a>, <a data-file="108-instruction" href="https://www.flaticon.com/authors/eucalyp">Eucalyp</a></p>
                    `
                }, {
                    name: "Ionic",
                    type: "Framework",
                    link: "https://github.com/ionic-team/ionic/blob/master/LICENSE",
                }, {
                    name: "React",
                    type: "Framework",
                    link: "https://github.com/facebook/react/blob/master/LICENSE",
                }, {
                    name: "Capacitor",
                    type: "Framework",
                    link: "https://github.com/ionic-team/capacitor/blob/master/LICENSE",
                }, {
                    name: "Bugsnag",
                    type: "Framework",
                    link: "https://docs.bugsnag.com/legal/terms-of-service/",
                }, {
                    name: "Material UI",
                    type: "Framework",
                    link: "https://github.com/mui-org/material-ui/blob/master/LICENSE",
                }, {
                    name: "Leaflet.js",
                    type: "Framework",
                    link: "https://github.com/Leaflet/Leaflet/blob/master/LICENSE",
                }, {
                    name: "react-google-autocomplete",
                    type: "Framework",
                    link: "https://github.com/ErrorPro/react-google-autocomplete/blob/master/LICENSE.md",
                }, {
                    name: "react-leaflet",
                    type: "Framework",
                    link: "https://github.com/PaulLeCam/react-leaflet/blob/master/LICENSE",
                }, {
                    name: "react-leaflet-markercluster",
                    type: "Framework",
                    link: "https://github.com/YUzhva/react-leaflet-markercluster/blob/master/LICENSE",
                }, {
                    name: "react-querybuilder",
                    type: "Framework",
                    link: "https://www.npmjs.com/package/react-querybuilder",
                }, {
                    name: "react-share",
                    type: "Framework",
                    link: "https://github.com/nygardk/react-share/blob/master/LICENSE",
                }, {
                    name: "react-tag-input",
                    type: "Framework",
                    link: "https://github.com/prakhar1989/react-tags/blob/master/LICENSE",
                }, {
                    name: "react-ga",
                    type: "Framework",
                    link: "https://github.com/react-ga/react-ga/blob/master/LICENSE",
                },

                {
                    name: "axios",
                    type: "Framework",
                    link: "https://github.com/axios/axios/blob/master/LICENSE",
                }, {
                    name: "compression",
                    type: "Framework",
                    link: "https://github.com/expressjs/compression/blob/master/LICENSE",
                }, {
                    name: "express",
                    type: "Framework",
                    link: "https://github.com/expressjs/express/blob/master/LICENSE",
                }, {
                    name: "express-jwt",
                    type: "Framework",
                    link: "https://github.com/auth0/express-jwt/blob/master/LICENSE",
                }, {
                    name: "express-rate-limit",
                    type: "Framework",
                    link: "https://github.com/nfriedly/express-rate-limit/blob/master/LICENSE",
                }, {
                    name: "jsonwebtoken",
                    type: "Framework",
                    link: "https://github.com/auth0/node-jsonwebtoken/blob/master/LICENSE",
                }, {
                    name: "multer",
                    type: "Framework",
                    link: "https://github.com/expressjs/multer/blob/master/LICENSE",
                }, {
                    name: "node-cron",
                    type: "Framework",
                    link: "https://github.com/node-cron/node-cron/blob/master/LICENSE.md",
                }, {
                    name: "nodemailer",
                    type: "Framework",
                    link: "https://github.com/nodemailer/nodemailer/blob/master/LICENSE",
                }, {
                    name: "object-hash",
                    type: "Framework",
                    link: "https://github.com/puleos/object-hash/blob/master/LICENSE",
                }, {
                    name: "passport",
                    type: "Framework",
                    link: "https://github.com/jaredhanson/passport/blob/master/LICENSE",
                }, {
                    name: "passport-local",
                    type: "Framework",
                    link: "https://github.com/jaredhanson/passport-local/blob/master/LICENSE",
                }, {
                    name: "pg",
                    type: "Framework",
                    link: "https://github.com/brianc/node-postgres/blob/master/LICENSE",
                }, {
                    name: "unzip",
                    type: "Framework",
                    link: "https://github.com/LuaDist/unzip/blob/master/LICENSE",
                }, {
                    name: "url-exists",
                    type: "Framework",
                    link: "https://github.com/boblauer/url-exists/blob/master/LICENSE",
                }, {
                    name: "csv-parser",
                    type: "Framework",
                    link: "https://github.com/mafintosh/csv-parser/blob/master/LICENSE",
                }, {
                    name: "parse-kml",
                    type: "Framework",
                    link: "https://www.npmjs.com/package/parse-kml",
                }, {
                    name: "parse-kmz",
                    type: "Framework",
                    link: "https://www.npmjs.com/package/parse-kmz",
                }, {
                    name: "shapefile",
                    type: "Framework",
                    link: "https://github.com/mbostock/shapefile/blob/master/LICENSE.txt",
                }, {
                    name: "read-excel-file",
                    type: "Framework",
                    link: "https://www.npmjs.com/package/read-excel-file",
                }, {
                    name: "xml2json",
                    type: "Framework",
                    link: "https://github.com/buglabs/node-xml2json",
                }
            ]
        }
    }

    ionViewWillEnter() {
        document.title = "Credits" + window.globalVars.pageTitle;
    }

    render() {
        return (
            <IonPage data-page="legal">
                <IonHeader>
                    <IonToolbar>
                        <IonButtons slot="start">
                        <IonBackButton onClick={() => { this.props.history.goBack();  }} />
                    </IonButtons>
                    <IonTitle>Credits</IonTitle>
                </IonToolbar>
                </IonHeader>
                <IonContent>
                    <IonList>
                        { (this.state.credits.map(item => {
                            return (
                                <IonItem key={item.name} mode="ios" style={{ "--min-height": '62px' }}>
                                    <IonLabel className="ion-text-wrap" position="stacked" onClick={() => { if (item.link) { window.open(item.link) } }}>
                                        <h2>{item.name}</h2>
                                        { (item.link) &&
                                            <h3>{item.link}</h3>
                                        }
                                        { (item.description) &&
                                            <p style={{ marginBottom: 8 }} dangerouslySetInnerHTML={{__html: item.description}}></p>
                                        }
                                    </IonLabel>
                                </IonItem>
                            )
                        })) }
                    </IonList>
                </IonContent>
            </IonPage>
        );
    }

};

export default withIonLifeCycle(Legal);
